### ISSUE TITLE
Problema de CORS

### ISSUE THREAD

**Issue by francescarpi** [pygrn/todos_django#1]
Bones. Tinc un problema de CORS.

![image](https://user-images.githubusercontent.com/287872/32575194-a755ba8a-c4d3-11e7-9cbf-eb43013272d1.png)

De moment podries desactivar la protecció de CORS (https://github.com/ottoyiu/django-cors-headers) i ja quan ho tingui penjat (igual a github pages), ja ho configurarem per que sigui consumida des d'aquest host.

Merci.

**Comment by manelclos** [comment]
Bones Francesc, ja ho he afegit.

**Comment by francescarpi** [comment]
Tot funcionant perfectament.
